
import React, { createContext, useContext, useState, useEffect } from 'react';

// --- NEW DATA STRUCTURES ---

export interface ContractClause {
  id: string;
    title: string;
      content: string;
        risk: 'safe' | 'caution' | 'danger';
          suggestion: string;
          }

          export interface ContractAnalysisData {
            contract: {
                title: string;
                    clauses: ContractClause[];
                        fullContent: string;
                          };
                            summary: {
                                score: number;
                                    status: string;
                                        description: string;
                                            risks: Array<{ level: string; count: number }>;
                                              };
                                              }

                                              export interface UserDraft {
                                                id: string;
                                                  originalTemplateId: string;
                                                    name: string;
                                                      content: string;
                                                        lastSaved: string;
                                                        }

                                                        export interface UserInspection {
                                                          id:string;
                                                            name: string;
                                                              createdAt: string;
                                                                score: number;
                                                                  content: string;
                                                                    analysisData?: ContractAnalysisData;
                                                                    }

                                                                    // --- UPDATED USER TYPE ---
                                                                    type User = {
                                                                      id: string;
                                                                        email: string;
                                                                          username: string;
                                                                            securityQuestion?: string;
                                                                              securityAnswer?: string;
                                                                                fullName?: string;
                                                                                  phone?: string;
                                                                                    birthdate?: string;
                                                                                      gender?: string;
                                                                                        avatar?: string;
                                                                                          templates: UserDraft[];
                                                                                            inspections: UserInspection[];
                                                                                            };

                                                                                            type Session = {
                                                                                              user: User;
                                                                                              };

                                                                                              // --- UPDATED CONTEXT TYPE ---
                                                                                              type AuthContextType = {
                                                                                                session: Session | null;
                                                                                                  user: User | null;
                                                                                                    loading: boolean;
                                                                                                      signIn: (username: string, password: string) => Promise<{ error: Error | null }>;
                                                                                                        signUp: (email: string, password: string, metadata: { username: string, securityQuestion: string, securityAnswer: string }) => Promise<{ error: Error | null }>;
                                                                                                          signOut: () => Promise<{ error: Error | null }>;
                                                                                                            requestPasswordReset: (email: string) => Promise<{ error: Error | null }>;
                                                                                                              updatePassword: (email: string, newPassword: string) => Promise<{ error: Error | null }>;
                                                                                                                updateUserProfile: (data: Partial<User>) => Promise<{ error: Error | null }>;
                                                                                                                };

                                                                                                                const AuthContext = createContext<AuthContextType | undefined>(undefined);

                                                                                                                export const AuthProvider = ({ children }: { children: React.ReactNode }) => {
                                                                                                                  const [session, setSession] = useState<Session | null>(null);
                                                                                                                    const [user, setUser] = useState<User | null>(null);
                                                                                                                      const [loading, setLoading] = useState(true);

                                                                                                                        useEffect(() => {
                                                                                                                            try {
                                                                                                                                  const storedSession = localStorage.getItem('session');
                                                                                                                                        if (storedSession) {
                                                                                                                                                const parsedSession: Session = JSON.parse(storedSession);
                                                                                                                                                        setSession(parsedSession);
                                                                                                                                                                const currentUser = parsedSession.user;
                                                                                                                                                                        if (!currentUser.templates) currentUser.templates = [];
                                                                                                                                                                                if (!currentUser.inspections) currentUser.inspections = [];
                                                                                                                                                                                        setUser(currentUser);
                                                                                                                                                                                              }
                                                                                                                                                                                                  } catch (error) {
                                                                                                                                                                                                        console.error('Failed to parse session from localStorage', error);
                                                                                                                                                                                                            } finally {
                                                                                                                                                                                                                  setLoading(false);
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                          const signIn = async (username: string, password: string): Promise<{ error: Error | null }> => {
                                                                                                                                                                                                                              const users: User[] = JSON.parse(localStorage.getItem('users') || '[]');
                                                                                                                                                                                                                                  const userExists = users.find(u => u.username === username);
                                                                                                                                                                                                                                      const storedPassword = localStorage.getItem(`password_${userExists?.id}`);

                                                                                                                                                                                                                                          if (userExists && storedPassword === password) {
                                                                                                                                                                                                                                                if (!userExists.templates) userExists.templates = [];
                                                                                                                                                                                                                                                      if (!userExists.inspections) userExists.inspections = [];

                                                                                                                                                                                                                                                            const currentSession: Session = { user: userExists };
                                                                                                                                                                                                                                                                  localStorage.setItem('session', JSON.stringify(currentSession));
                                                                                                                                                                                                                                                                        setSession(currentSession);
                                                                                                                                                                                                                                                                              setUser(userExists);
                                                                                                                                                                                                                                                                                    return { error: null };
                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                              return { error: new Error('Tên đăng nhập hoặc mật khẩu không đúng') };
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                      const signUp = async (email: string, password: string, metadata: { username: string, securityQuestion: string, securityAnswer: string }): Promise<{ error: Error | null }> => {
                                                                                                                                                                                                                                                                                                          const users: User[] = JSON.parse(localStorage.getItem('users') || '[]');

                                                                                                                                                                                                                                                                                                              if (users.some(u => u.email === email)) {
                                                                                                                                                                                                                                                                                                                    return { error: new Error('Một tài khoản với email này đã tồn tại.') };
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                            if (users.some(u => u.username === metadata.username)) {
                                                                                                                                                                                                                                                                                                                                  return { error: new Error('Tên đăng nhập này đã được sử dụng.') };
                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                          const newUser: User = {
                                                                                                                                                                                                                                                                                                                                                id: `user_${Date.now()}`,
                                                                                                                                                                                                                                                                                                                                                      email,
                                                                                                                                                                                                                                                                                                                                                            username: metadata.username,
                                                                                                                                                                                                                                                                                                                                                                  securityQuestion: metadata.securityQuestion,
                                                                                                                                                                                                                                                                                                                                                                        securityAnswer: metadata.securityAnswer,
                                                                                                                                                                                                                                                                                                                                                                              fullName: '', 
                                                                                                                                                                                                                                                                                                                                                                                    phone: '',
                                                                                                                                                                                                                                                                                                                                                                                          birthdate: '',
                                                                                                                                                                                                                                                                                                                                                                                                gender: '',
                                                                                                                                                                                                                                                                                                                                                                                                      avatar: '',
                                                                                                                                                                                                                                                                                                                                                                                                            templates: [],
                                                                                                                                                                                                                                                                                                                                                                                                                  inspections: [],
                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                          users.push(newUser);
                                                                                                                                                                                                                                                                                                                                                                                                                              localStorage.setItem('users', JSON.stringify(users));
                                                                                                                                                                                                                                                                                                                                                                                                                                  localStorage.setItem(`password_${newUser.id}`, password);

                                                                                                                                                                                                                                                                                                                                                                                                                                      // Do not sign in automatically, let user login
                                                                                                                                                                                                                                                                                                                                                                                                                                          // const newSession: Session = { user: newUser };
                                                                                                                                                                                                                                                                                                                                                                                                                                              // localStorage.setItem('session', JSON.stringify(newSession));
                                                                                                                                                                                                                                                                                                                                                                                                                                                  // setSession(newSession);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      // setUser(newUser);

                                                                                                                                                                                                                                                                                                                                                                                                                                                          return { error: null };
                                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const requestPasswordReset = async (email: string): Promise<{ error: Error | null }> => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const users: User[] = JSON.parse(localStorage.getItem('users') || '[]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const userExists = users.find(u => u.email === email);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!userExists) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { error: new Error('Không tìm thấy tài khoản nào với địa chỉ email này.') };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // In a real app, you would generate a secure token and send an email.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Here, we'll simulate it by logging to the console and creating a simple token.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const token = `reset_${userExists.id}_${Date.now()}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`Password reset link for ${email}: /reset-password?token=${token}&email=${encodeURIComponent(email)}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // You can use a service like SendGrid, Mailgun, etc. to send actual emails.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // For this example, we just return success.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { error: null };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const signOut = async (): Promise<{ error: Error | null }> => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                localStorage.removeItem('session');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setSession(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setUser(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return { error: null };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const updatePassword = async (email: string, newPassword: string): Promise<{ error: Error | null }> => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const users: User[] = JSON.parse(localStorage.getItem('users') || '[]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const userToUpdate = users.find(u => u.email === email);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!userToUpdate) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { error: new Error('Người dùng không tồn tại.') };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            localStorage.setItem(`password_${userToUpdate.id}`, newPassword);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { error: null };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const updateUserProfile = async (data: Partial<User>): Promise<{ error: Error | null }> => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!user) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return { error: new Error("Không có người dùng nào đang đăng nhập.") };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const users: User[] = JSON.parse(localStorage.getItem('users') || '[]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const userIndex = users.findIndex(u => u.id === user.id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (userIndex === -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { error: new Error("Không tìm thấy người dùng trong cơ sở dữ liệu.") };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (data.username && data.username !== users[userIndex].username) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (users.some(u => u.username === data.username)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return { error: new Error('Tên người dùng này đã được sử dụng.') };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const updatedUser: User = { ...users[userIndex], ...data };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              users[userIndex] = updatedUser;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    localStorage.setItem('users', JSON.stringify(users));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setUser(updatedUser);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const updatedSession: Session = { user: updatedUser };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setSession(updatedSession);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            localStorage.setItem('session', JSON.stringify(updatedSession));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { error: null };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (e: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return { error: new Error("Không thể cập nhật hồ sơ: " + e.message) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const value = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              session,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  user,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      loading,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          signIn,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              signUp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  signOut,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      requestPasswordReset,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          updatePassword,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              updateUserProfile,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <AuthContext.Provider value={value}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {!loading && children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </AuthContext.Provider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export const useAuth = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const context = useContext(AuthContext);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (context === undefined) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          throw new Error('useAuth phải được sử dụng trong một AuthProvider');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return context;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              