import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { jsPDF } from "jspdf"; // Import thư viện tạo PDF
import { 
  Zap, Search, Plus, FileText, FileCheck, 
  AlertTriangle, Clock, ChevronRight, MoreHorizontal, Trash2, Eye, Download 
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

// Định nghĩa kiểu dữ liệu
interface Contract {
  id: number;
  name: string;
  type: string;
  score: number;
  timestamp: string;
  status: string;
}

const Dashboard = () => {
  const navigate = useNavigate();
  
  const [stats, setStats] = useState({
    total: 0,
    completed: 0,
    highRisk: 0
  });

  const [recentDocs, setRecentDocs] = useState<Contract[]>([]);

  // --- HÀM TẢI PDF ---
  const handleDownload = (docName: string, score: number) => {
    // 1. Khởi tạo PDF
    const doc = new jsPDF();

    // 2. Tiêu đề
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229); // Màu tím xanh (Agreeme Brand)
    doc.text("AGREEME ANALYSIS REPORT", 20, 25);

    // 3. Thông tin chung
    doc.setTextColor(0, 0, 0); // Màu đen
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`File Name: ${docName}`, 20, 45);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 55);
    
    // Điểm số
    doc.setFont("helvetica", "bold");
    doc.text(`Health Score: ${score}/100`, 20, 65);

    // Kẻ đường
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 75, 190, 75);

    // 4. Nội dung tóm tắt
    doc.setFontSize(14);
    doc.text("Executive Summary:", 20, 90);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    const statusText = score >= 80 ? "Safe" : (score >= 60 ? "Caution" : "High Risk");
    
    const content = `
    This document has been processed by Agreeme's AI Engine.
    
    - Overall Status: ${statusText}
    - Compliance Check: Completed
    - Risk Assessment: ${score < 60 ? "Critical issues found." : "Standard compliance met."}
    
    For a detailed breakdown of specific clauses and legal recommendations, 
    please refer to the full interactive report on the dashboard.
    `;
    
    // In nội dung (tự động xuống dòng nếu dài)
    doc.text(content, 20, 100);

    // 5. Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Agreeme AI Platform", 20, 280);

    // 6. Lưu file
    doc.save(`${docName.replace(/\s+/g, '_')}_report.pdf`);
  };

  const updateDashboardData = (contracts: Contract[]) => {
    const total = contracts.length;
    const completed = contracts.filter(c => c.status === 'Completed').length;
    const highRisk = contracts.filter(c => c.score < 60).length;

    setStats({ total, completed, highRisk });
    setRecentDocs(contracts.slice(0, 5));
  };

  useEffect(() => {
    const savedData = localStorage.getItem('saved_contracts');
    
    if (savedData && JSON.parse(savedData).length > 0) {
      updateDashboardData(JSON.parse(savedData));
    } else {
      const now = new Date();
      const mockData: Contract[] = [
        {
          id: 1, name: "Thỏa thuận bảo mật thông tin (NDA)", type: "Contract Analysis", score: 95, timestamp: now.toISOString(), status: "Completed"
        },
        {
          id: 2, name: "Hợp đồng lao động - Nguyễn Văn A", type: "Contract Analysis", score: 88, timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(), status: "Completed"
        },
        {
          id: 3, name: "Hợp đồng thuê văn phòng 2025", type: "Contract Analysis", score: 72, timestamp: new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString(), status: "In Progress"
        },
      ];
      localStorage.setItem('saved_contracts', JSON.stringify(mockData));
      updateDashboardData(mockData);
    }
  }, []);

  const handleDelete = (id: number) => {
    const savedData = localStorage.getItem('saved_contracts');
    if (!savedData) return;
    const contracts: Contract[] = JSON.parse(savedData);
    const newContracts = contracts.filter(c => c.id !== id);
    localStorage.setItem('saved_contracts', JSON.stringify(newContracts));
    updateDashboardData(newContracts);
  };

  const formatTimeAgo = (isoString: string) => {
    if (!isoString) return "Just now";
    const diff = new Date().getTime() - new Date(isoString).getTime();
    const hours = Math.floor(diff / (1000 * 60 * 60));
    const days = Math.floor(hours / 24);
    if (days > 0) return `${days} days ago`;
    if (hours > 0) return `${hours} hours ago`;
    return "Just now";
  };

  const getScoreBadge = (score: number) => {
    if (score >= 80) return <span className="bg-emerald-100 text-emerald-700 border border-emerald-200 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1 shadow-sm"><FileCheck size={12} /> Safe ({score}%)</span>;
    if (score >= 60) return <span className="bg-orange-100 text-orange-700 border border-orange-200 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1 shadow-sm"><AlertTriangle size={12} /> Caution ({score}%)</span>;
    return <span className="bg-red-100 text-red-700 border border-red-200 px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1 shadow-sm"><AlertTriangle size={12} /> High Risk ({score}%)</span>;
  };

  return (
    <div className="p-6 max-w-[1600px] mx-auto font-sans text-slate-700">
      
      {/* HERO BANNER */}
      <div className="bg-gradient-to-r from-[#1e1b4b] to-[#4F46E5] rounded-3xl p-10 text-white shadow-xl relative overflow-hidden mb-10">
        <div className="relative z-10 max-w-2xl">
          <h1 className="text-3xl font-bold mb-4">Welcome back, Admin!</h1>
          <h2 className="text-xl font-medium opacity-90 mb-6">Start your automated contract analysis.</h2>
          <p className="opacity-80 mb-8 leading-relaxed max-w-lg">Use AI to scan for risks, manage templates, and ensure compliance across all your legal documents in seconds.</p>
          <div className="flex gap-4">
            <Button onClick={() => navigate('/deep-analysis')} className="bg-white text-[#4F46E5] hover:bg-slate-100 font-bold px-6 py-5 rounded-xl flex items-center gap-2 border-none"><Zap size={18} fill="currentColor"/> Quick Review</Button>
            <Button onClick={() => navigate('/deep-analysis')} className="bg-transparent border border-white/30 text-white hover:bg-white/10 px-6 py-5 rounded-xl font-medium">Deep Analysis</Button>
          </div>
        </div>
        <div className="absolute top-0 right-0 w-1/2 h-full bg-[url('https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=2664&auto=format&fit=crop')] bg-cover opacity-20 mix-blend-overlay mask-image-linear-gradient" style={{ maskImage: 'linear-gradient(to left, black, transparent)' }}></div>
      </div>

      {/* QUICK ACTIONS */}
      <div className="mb-10">
        <div className="flex justify-between items-center mb-4"><h3 className="font-bold text-slate-800 text-lg">Quick Actions</h3><span className="text-sm text-[#4F46E5] font-medium cursor-pointer hover:underline">View all</span></div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div onClick={() => navigate('/deep-analysis')} className="bg-white p-5 rounded-2xl border border-slate-200 hover:shadow-md hover:border-[#4F46E5] cursor-pointer transition-all group"><div className="w-10 h-10 bg-blue-50 text-[#4F46E5] rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform"><Zap size={20} /></div><div className="flex justify-between items-start"><div><h4 className="font-bold text-slate-800 text-sm">Quick Review</h4><p className="text-xs text-slate-500 mt-1">Scan PDF/Docx instantly</p></div><ChevronRight size={16} className="text-slate-300 group-hover:text-[#4F46E5]"/></div></div>
            <div onClick={() => navigate('/deep-analysis')} className="bg-white p-5 rounded-2xl border border-slate-200 hover:shadow-md hover:border-[#4F46E5] cursor-pointer transition-all group"><div className="w-10 h-10 bg-blue-50 text-[#4F46E5] rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform"><Search size={20} /></div><div className="flex justify-between items-start"><div><h4 className="font-bold text-slate-800 text-sm">Deep Analysis</h4><p className="text-xs text-slate-500 mt-1">Detailed risk report</p></div><ChevronRight size={16} className="text-slate-300 group-hover:text-[#4F46E5]"/></div></div>
            <div onClick={() => navigate('/templates')} className="bg-white p-5 rounded-2xl border border-slate-200 hover:shadow-md hover:border-[#4F46E5] cursor-pointer transition-all group"><div className="w-10 h-10 bg-purple-50 text-purple-600 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform"><Plus size={20} /></div><div className="flex justify-between items-start"><div><h4 className="font-bold text-slate-800 text-sm">Create Contract</h4><p className="text-xs text-slate-500 mt-1">Use AI templates</p></div><ChevronRight size={16} className="text-slate-300 group-hover:text-[#4F46E5]"/></div></div>
            <div onClick={() => navigate('/templates')} className="bg-white p-5 rounded-2xl border border-slate-200 hover:shadow-md hover:border-[#4F46E5] cursor-pointer transition-all group"><div className="w-10 h-10 bg-orange-50 text-orange-600 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform"><FileText size={20} /></div><div className="flex justify-between items-start"><div><h4 className="font-bold text-slate-800 text-sm">Templates Library</h4><p className="text-xs text-slate-500 mt-1">Browse standard forms</p></div><ChevronRight size={16} className="text-slate-300 group-hover:text-[#4F46E5]"/></div></div>
        </div>
      </div>

      {/* SUMMARY STATS */}
      <div className="mb-10">
        <h3 className="font-bold text-slate-800 text-lg mb-4">Summary</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white p-6 rounded-2xl border border-slate-200 flex items-center gap-5 shadow-sm"><div className="w-14 h-14 bg-blue-50 text-[#4F46E5] rounded-full flex items-center justify-center"><FileText size={24} /></div><div><h4 className="text-3xl font-bold text-slate-800">{stats.total}</h4><p className="text-sm text-slate-500 mt-1">Total Contracts</p></div></div>
            <div className="bg-white p-6 rounded-2xl border border-slate-200 flex items-center gap-5 shadow-sm"><div className="w-14 h-14 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center"><FileCheck size={24} /></div><div><h4 className="text-3xl font-bold text-slate-800">{stats.completed}</h4><p className="text-sm text-slate-500 mt-1">Reviews Completed</p></div></div>
            <div className="bg-white p-6 rounded-2xl border border-slate-200 flex items-center gap-5 shadow-sm"><div className="w-14 h-14 bg-red-50 text-red-600 rounded-full flex items-center justify-center"><AlertTriangle size={24} /></div><div><h4 className="text-3xl font-bold text-slate-800">{stats.highRisk}</h4><p className="text-sm text-slate-500 mt-1">High Risk Found</p></div></div>
        </div>
      </div>

      {/* RECENT ACTIVITY */}
      <div>
        <div className="flex justify-between items-center mb-4">
             <div className="flex items-center gap-3"><h3 className="font-bold text-slate-800 text-lg">In Progress</h3><span className="bg-blue-100 text-[#4F46E5] text-xs font-bold px-2 py-1 rounded-full">{recentDocs.length}</span></div>
             <span className="text-sm text-[#4F46E5] font-medium cursor-pointer hover:underline" onClick={() => navigate('/inspections')}>View all documents</span>
        </div>

        <div className="bg-white border border-slate-200 rounded-2xl overflow-visible shadow-sm">
            {recentDocs.length > 0 ? (
                recentDocs.map((doc) => (
                    <div key={doc.id} className="p-4 border-b border-slate-100 hover:bg-slate-50 transition-colors flex items-center justify-between last:border-0 group">
                        
                        <div className="flex items-center gap-4">
                            <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${doc.score >= 80 ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}><FileText size={20} /></div>
                            <div><h4 className="font-bold text-slate-800 text-sm cursor-pointer hover:text-[#4F46E5]" onClick={() => navigate('/deep-analysis')}>{doc.name}</h4><div className="flex items-center gap-2 mt-1"><Clock size={12} className="text-slate-400"/><span className="text-xs text-slate-400">Modified {formatTimeAgo(doc.timestamp)}</span></div></div>
                        </div>

                        <div className="flex items-center gap-6">
                            {getScoreBadge(doc.score)}
                            
                            {/* MENU ACTIONS */}
                            <DropdownMenu>
                                <DropdownMenuTrigger asChild>
                                    <button className="text-slate-400 hover:text-slate-600 p-2 hover:bg-slate-200 rounded-full transition-colors focus:outline-none">
                                        <MoreHorizontal size={20} />
                                    </button>
                                </DropdownMenuTrigger>
                                <DropdownMenuContent align="end" className="w-48">
                                    <DropdownMenuItem onClick={() => navigate('/inspections')} className="cursor-pointer">
                                        <Eye className="mr-2 h-4 w-4" /> View details
                                    </DropdownMenuItem>
                                    
                                    {/* MỤC DOWNLOAD PDF */}
                                    <DropdownMenuItem onClick={() => handleDownload(doc.name, doc.score)} className="cursor-pointer">
                                        <Download className="mr-2 h-4 w-4" /> Download PDF
                                    </DropdownMenuItem>

                                    <DropdownMenuSeparator />
                                    
                                    <DropdownMenuItem onClick={() => handleDelete(doc.id)} className="text-red-600 cursor-pointer focus:text-red-600 focus:bg-red-50">
                                        <Trash2 className="mr-2 h-4 w-4" /> Delete
                                    </DropdownMenuItem>
                                </DropdownMenuContent>
                            </DropdownMenu>
                        </div>
                    </div>
                ))
            ) : (
                <div className="p-10 text-center text-slate-400"><p>No recent activity.</p></div>
            )}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;